<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Company dynamic costs' => '',
    'Company static costs' => '',
    'Dynamic cost name' => '',
    'Dynamic cost value' => '',
    'E-mail' => '',
    'Other expenses' => '',
    'Personal expenses' => '',
    'company data' => '',
    'Add dynamic cost' => 'Pridať novú položku',
    'Company' => 'Firma',
    'Company name' => 'Názov spoločnosti',
    'DIC' => 'DIČ',
    'IC DPH' => 'IČ DPH',
    'ICO' => 'IČO',
    'Phone' => 'Tel.číslo',
    'Update' => 'Aktualizovať položku',
    'You does not defined your company. Create one!' => 'Nemáte zadefinované firemné údaje. Vyplňte ich!',
    'company data for {companyName}' => 'firemné údaje firmu {companyName}',
];
