<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Clients list' => 'Adresár klientov',
    'Company admin' => 'Firemné administrácie',
    'Company expenses' => 'Firemné výdavky',
    'Create diver' => 'Vytvoriť vodiča',
    'Create listings record' => 'Pridať novú adresu',
    'Create toll' => 'Nahrať colnicu',
    'Create un/load place' => 'Pridať',
    'Create user' => 'Vytvoriť nového užívateľa',
    'Create vehicle' => 'Pridať vozidlo ',
    'Driver' => 'Vodič',
    'Drivers list' => 'Zoznam vodičov',
    'Expenses' => 'Výdavky',
    'Expenses settings' => 'Použité výdavky',
    'Listings' => 'Zoznamy',
    'Loads and unloads' => 'Nakládky a vykládky',
    'Loads and unloads list' => 'Zoznam nakládkov/vykládkov',
    'Services list' => 'Adresár servisov',
    'Tolls' => 'Colnice',
    'Tolls list' => 'Zoznam colníc',
    'Users Management' => 'Používatelia',
    'Users list' => 'Zoznam užívateľov',
    'Vehicle' => 'Vozidlo',
    'Vehicles list' => 'Zoznam vozidiel',
    'Dashboard' => 'Ovládací panel',
];
