<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Value should be numeric {value}' => '',
    'adm_buy_thnc' => 'Nákup techniky',
    'adm_disp_rbsh' => 'Komunálne náklady',
    'adm_prev' => 'Prev.režia',
    'adm_rntl' => 'Prenájom a odpis',
    'lsng' => '',
    'mass_acc_ins' => 'Zodpovedné poistenie',
    'mass_cls_ins' => 'Havarijné poistenie',
    'mass_cmr_ins' => 'CMR poistenie',
    'mass_req_ins' => 'PZP',
    'privtmc' => '',
    'cmins' => 'PZP',
    'cmrins' => 'CMR poistenie',
    'colins' => 'Havarijné poistenie',
    'cslr' => 'Fixná mzda + odvody',
    'ldng' => 'Za vykládky/nakládky',
    'ldng_dual' => 'Za vykládky/nakládky',
    'lnch' => 'Stravné na deň',
    'lnch_dual' => 'Stravné na deň',
    'mnvhcl' => 'Tahač/Vozidlo',
    'mnvhcl_trlr_empty' => 'Tahač s návesom prázdny',
    'mnvhcl_trlr_weight' => 'Tahač s návaseom prírastok na tonu',
    'otha' => 'Iné náklady A',
    'othb' => 'Iné náklady B',
    'pnmt' => 'Pneu amortizácia',
    'privtma' => 'Vlastné časové náklady A',
    'privtmb' => 'Vlastné časové náklady B',
    'rdtx' => 'Cestná daň',
    'srvs' => 'Servisné náklady',
    'wgfr' => 'Mzda na km',
    'wgfr_dual' => 'Mzda na km',
];
