<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'adm_buy_thnc' => '',
    'adm_disp_rbsh' => '',
    'adm_prev' => '',
    'adm_rntl' => '',
    'cmins' => '',
    'cmrins' => '',
    'colins' => '',
    'cslr' => 'Fixná mzda + odvody',
    'ldng' => 'Za vykládky/nakládky',
    'ldng_dual' => 'Za vykládky/nakládky',
    'lnch' => 'Stravné na deň',
    'lnch_dual' => 'Stravné na deň',
    'mass_acc_ins' => '',
    'mass_cls_ins' => '',
    'mass_cmr_ins' => '',
    'mass_req_ins' => '',
    'mnvhcl' => '',
    'mnvhcl_trlr_empty' => '',
    'mnvhcl_trlr_weight' => '',
    'otha' => '',
    'othb' => '',
    'pnmt' => '',
    'privtma' => '',
    'privtmb' => '',
    'rdtx' => '',
    'srvs' => '',
    'wgfr' => 'Mzda na km',
    'wgfr_dual' => 'Mzda na km',
    'leasing' => 'Leasing/Amortizácia',
];
