<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A password will be generated automatically if not provided' => '',
    'Account' => '',
    'Account details' => '',
    'Account settings' => '',
    'Already registered? Sign in!' => '',
    'Are you sure you want to block this user?' => '',
    'Are you sure you want to confirm this user?' => '',
    'Are you sure you want to delete this user?' => '',
    'Are you sure you want to switch to this user for the rest of this Session?' => '',
    'Are you sure you want to unblock this user?' => '',
    'Are you sure?' => '',
    'Are you sure? There is no going back' => '',
    'Assignments' => '',
    'Become this user' => '',
    'Block' => '',
    'Block status' => '',
    'Blocked at {0, date, MMMM dd, YYYY HH:mm}' => '',
    'Confirm' => '',
    'Confirmation' => '',
    'Confirmation status' => '',
    'Confirmed' => '',
    'Confirmed at {0, date, MMMM dd, YYYY HH:mm}' => '',
    'Continue' => '',
    'Create' => '',
    'Create a user account' => '',
    'Credentials will be sent to the user by email' => '',
    'Delete' => '',
    'Delete account' => '',
    'Didn\'t receive confirmation message?' => '',
    'Enter your details to create your account:' => '',
    'Fill in company info!' => '',
    'Finish' => '',
    'Forgotten password?' => '',
    'Generate and send new password to user' => '',
    'If you already registered, sign in and connect this account on settings page' => '',
    'In order to finish your registration, we need you to enter following fields' => '',
    'Information' => '',
    'It will be deleted forever' => '',
    'Manage users' => '',
    'Never' => '',
    'New permission' => '',
    'New role' => '',
    'New rule' => '',
    'New user' => '',
    'Not blocked' => '',
    'Once you delete your account, there is no going back' => '',
    'Permissions' => '',
    'Please be certain' => '',
    'Prihlásiť sa' => '',
    'Profile' => '',
    'Profile details' => '',
    'Profile settings' => '',
    'Recover your password' => '',
    'Registration IP' => '',
    'Registration time' => '',
    'Registrácia!' => '',
    'Request new confirmation message' => '',
    'Request new password' => '',
    'Reset your password' => '',
    'Roles' => '',
    'Rules' => '',
    'Sign in' => '',
    'Sign up' => '',
    'Unblock' => '',
    'Unconfirmed' => '',
    'Update' => '',
    'Update user account' => '',
    'User was added into company!' => '',
    'Users' => '',
    'You can assign multiple roles or permissions to user by using the form below' => '',
    'Your account details have been updated' => '',
    'Your account has been created and a message with further instructions has been sent to your email' => '',
    'Your profile has been updated' => '',
    '{0, date, MMMM dd, YYYY HH:mm}' => '',
];
